export const actionType = {
  FETCH_JOB_DETAIL_SUCCESS: "FETCH_JOB_DETAIL_SUCCESS",
  FETCH_JOB_DETAIL_FAILURE: "FETCH_JOB_DETAIL_FAILURE",
  FETCH_JOB_DETAIL_RESET: "FETCH_JOB_DETAIL_RESET",
  FETCH_JOB_DETAIL_LOADING: "FETCH_JOB_DETAIL_LOADING",
};
