export const actionType = {
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAILURE: "USER_LOGIN_FAILURE",
  USER_LOGIN_RESET: "USER_LOGIN_RESET",
  USER_LOGIN_LOADING: "USER_LOGIN_LOADING",
  USER_LOGOUT: "USER_LOGOUT",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE",
  USER_REGISTER_RESET: "USER_REGISTER_RESET",
  USER_REGISTER_LOADING: "USER_REGISTER_LOADING",
  USER_TOKEN_SUCCESS: "USER_TOKEN_SUCCESS",
  USER_TOKEN_FAILURE: "USER_TOKEN_FAILURE",
};
