export const actionType = {
  FETCH_JOB_DATA_SUCCESS: "FETCH_JOB_DATA_SUCCESS",
  FETCH_JOB_DATA_FAILURE: "FETCH_JOB_DATA_FAILURE",
  FETCH_JOB_DATA_RESET: "FETCH_JOB_DATA_RESET",
  FETCH_JOB_DATA_LOADING: "FETCH_JOB_DATA_LOADING",
  SORT_JOB_DATA: "SORT_JOB_DATA",
  POST_NEW_JOB_SUCCESS: "POST_NEW_JOB_SUCCESS",
  POST_NEW_JOB_FAILURE: "POST_NEW_JOB_FAILURE",
  POST_NEW_JOB_RESET: "POST_NEW_JOB_RESET",
  POST_NEW_JOB_LOADING: "POST_NEW_JOB_LOADING",
};
